print("🎲 MINI JUEGO DE CALABOZOS Y DRAGONES - REGLAS")
print()
print("1. CREA TU PERSONAJE:")
print("- Elige una clase: Guerrero (1d8), Mago (1d6 + 1 hechizo), Ladrón (1d6+1).")
print("- Todos comienzan con 10 puntos de vida (PV).")
print()
print("2. COMBATE:")
print("- Peleas contra un enemigo lanzando dados para hacer daño.")
print("- El enemigo también ataca en su turno.")
print("- El combate termina cuando uno llegue a 0 PV.")
print()
print("3. HABILIDADES ESPECIALES:")
print("- Mago: Puede lanzar un hechizo poderoso una vez.")
print("- Ladrón: Tiene +1 al daño.")
print("- Guerrero: Tiene el dado más fuerte (1d8).")
print()
print("4. FINAL DEL JUEGO:")
print("- Si el enemigo muere, ganas.")
print("- Si tus PV bajan a 0, pierdes.")
print()

